version: "3.10"
networks:
  net:
    external: true
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      - POSTGRES_PASSWORD=HelloMBDS
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    networks:
      - net
    environment:
      PGADMIN_DEFAULT_EMAIL: mbds@mbds.com
      PGADMIN_DEFAULT_PASSWORD: HelloMBDS
    ports:
      - "5050:80"
volumes:
  postgres-data: